<?php

/**
 * The class table handles the creation of the html code for a table at the web page.
 */
class Table
{

    private $tableHead = [];
    private $tableData = [];
    private $tableColumns = 0;
    private $rowID = [];


    /**
     * The function setTableHead expects an array with the content of the table heads.
     * It iterates the array, saves the content into the tablehead variable and counts the number of heads.
     * The number of heads where used to determine how many columns the table have.
     *
     * @param $tableHead
     */

    public function setTableHead($tableHead)
    {
        $i = 0;
        foreach ($tableHead as $head) {
            $this->tableHead[$i] = $head;
            $i++;
        }
        $rows = $i;
        $this->setTableColumns($rows);

    }


    /**
     * The function setTableColumns expects the number of columns.
     * It where saved in the class variable tableColumns
     *
     * @param $columns
     */

    public function setTableColumns($columns)
    {
        $this->tableColumns = $columns;
    }


    /**
     * The function addTableContent expects the a content strings that
     * where added to the content array at the last position.
     *
     * @param $content
     */

    public function addTableContent($content)
    {
        $index = count($this->tableData);

        $this->tableData[$index] = $content;

        if ($index % $this->tableColumns == 0) {
            $this->newRowID();
        }

    }


    /**
     * The function getHTML returns the html code generated by the content like the heads and content
     * added to the class earlier.
     *
     * @return string
     */

    public function getHTML()
    {
        $rowIDs = $this->rowID;
        $numberOfColumns = $this->tableColumns;
        $html = "";
        $rowCounter = 0;

        $html .= "<table class='table'>";

        if ($this->tableHead != null) {
            $html .= "<tr>";

            foreach ($this->tableHead as $head) {
                $html .= "<th>$head</th>";
            }
            $html .= "</tr>";
        }
        $html .= "<tr>";

        $i = 0;
        foreach ($this->tableData as $data) {
            if (($i) % $numberOfColumns == 0) {
                $html .= "</tr><tr id='$rowIDs[$rowCounter]'>";
                $rowCounter++;
            }
//
            $html .= "<td>$data</td>";
            $i++;

        }
        $html .= "</tr>";

        $html .= "</table>";

        return $html;

    }

    private function newRowID()
    {
        $id = DOM_id::getID();
        $index = count($this->rowID);
        $this->rowID[$index] = $id;
    }

    public function getCurrentRowID()
    {
        $index = count($this->rowID);
        return $this->rowID[$index - 1];
    }

}